version: '3.9'

x-logging: &logging
    logging:
        driver: 'json-file'
        options:
            max-file: '5'
            max-size: '10m'

x-restart-policy: &restart_policy
    restart: unless-stopped

services:
    nginx:
        <<: *logging
        <<: *restart_policy
        image: nginx:1.21.6-alpine
        container_name: nginx_server
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/cert.pem:/etc/nginx/cert.pem
            - ./nginx/key.pem:/etc/nginx/key.pem
        ports:
            - '80:80'
            - '443:443'
        depends_on:
            - api
        networks:
            - warstars

    postgres:
        <<: *logging
        <<: *restart_policy
        image: postgres:14-alpine
        container_name: warstars_database
        ports:
            - '5433:5433'
        env_file:
            - .env
        volumes:
            - warstars:/var/lib/postgresql/data
        networks:
            - warstars

    redis:
        <<: *logging
        <<: *restart_policy
        image: 'redis:6.2.6-alpine'
        container_name: warstars_redis
        ports:
            - '127.0.0.1:6379:6379'
        networks:
            - warstars

    api:
        <<: *logging
        <<: *restart_policy
        image: ghcr.io/r-priyam/warstars-api:latest
        container_name: warstars_api
        env_file:
            - .env
        ports:
            - '${PORT}:${PORT}'
        volumes:
            - ./logs:/logs
        depends_on:
            - postgres
            - redis
        networks:
            - warstars

volumes:
    warstars:
        name: warstars

networks:
  warstars:
    driver: bridge
