version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    container_name: WarStars-DB
    restart: always
    ports:
      - 5433:5433
    env_file:
      - .env
    volumes:
      - warstars:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data

  api:
    container_name: WarStars-API
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres

volumes:
  warstars:
    name: warstars-db
