version: '3.9'

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"

x-restart-policy: &restart_policy
  restart: unless-stopped

services:
  postgres:
    << : *logging
    << : *restart_policy
    image: postgres:14-alpine
    container_name: warstars-database
    ports:
      - "5433:5433"
    env_file:
      - .env
    volumes:
      - warstars:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data

  api:
    << : *logging
    << : *restart_policy
    image: ghcr.io/r-priyam/warstars-api:latest
    container_name: warstars-api
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}" 
    volumes:
      - ./logs:/logs
    depends_on:
      - postgres

volumes:
  warstars:
    name: warstars
