version: '3.9'

x-logging: &logging
    logging:
        driver: 'json-file'
        options:
            max-file: '1'
            max-size: '5m'

x-restart-policy: &restart_policy
    restart: unless-stopped

services:
    postgres:
        <<: *logging
        <<: *restart_policy
        image: postgres:14-alpine
        container_name: warstars_database
        ports:
            - '5433:5433'
        env_file:
            - .env
        volumes:
            - warstars:/var/lib/postgresql/data

    redis:
        <<: *logging
        <<: *restart_policy
        image: 'redis:7.0.2-alpine'
        container_name: warstars_redis
        ports:
            - '127.0.0.1:6379:6379'

    api:
        <<: *logging
        container_name: warstars_api
        image: node:18.4-alpine
        volumes:
            - .:/app:rw
        working_dir: /app
        ports:
            - '8888:8888'
        command: npm run start:dev
        depends_on:
            - postgres
            - redis

volumes:
    warstars:
        name: warstars
